const Token = @import("Token.zig");
const TokenIndex = Token.TokenIndex;

pub const NodeIndex = u32;
pub const root_node_index: NodeIndex = 0;
pub const null_node_index: NodeIndex = 0;

main_token: TokenIndex,
node_type: NodeType,
left_side: NodeIndex,
right_side: NodeIndex,

pub fn a(main_token: TokenIndex, node_type: NodeType, left_side: NodeIndex, right_side: NodeIndex) Node {
    const self = Node{
        .node_type = node_type,
        .main_token = main_token,
        .left_side = left_side,
        .right_side = right_side,
    };
    return self;
}

pub const NodeType = enum {
    unkown,
    import_func,
    include_func,
    define_var,
    type_decl,
    fn_param,
    assign,
    merge_error_sets,
    array_mult,
    array_type,
    array_access,
    array_init,
    array_init_comma,
    array_init_value,
    type_expr,
    align_type,
    callconv_type,
    slice,
    slice_sentinel,
    optional_type,
    pointer_type,
    deref,
    unwrap_optional,
    error_value,
    error_union,
    add,
    array_cat,
    sub,
    mul,
    div,
    mod,
    negation,
    shl,
    shr,
    bit_and,
    bit_xor,
    bit_or,
    bit_not,
    bool_and,
    bool_or,
    bool_not,
    address_of,
    _catch,
    _try,
    call_fn,
    fn_type,
    func_init,
    func_init_arg_list,
    func_init_arg,
    func_init_dot,
    fn_arg,
    _comptime,
    case_arg,
    catch_body,
    equal_equal,
    bang_equal,
    less_than,
    greater_than,
    less_or_equal,
    greater_or_equal,
    identifier,
    char_literal,
    number_literal,
    field_access,
    string_literal,
    multiline_string_literal,
    grouped_expression,
    container_decl,
    container_field,
    _continue,
    _break,
    _unreachable,
    _return,
    define_fn,
    fn_proto,
    _block,
    empty_block,
    if_else_line,
    if_block,
    else_block,
    else_if_block,
    for_block,
    while_block,
    switch_block,
    switch_case_block,
    switch_range,
    asm_simple,
    code_simple,
    test_block,
    _defer,
    _errdefer,
};

const Node = @This();
