const DataType = @import("../../system/DataType.zig");
const StaticStringMap = DataType.StaticStringMap;

pub const CharIndex = usize;
pub const null_char_index: CharIndex = 0;
pub const TokenIndex = u32;

token_type: TokenType,
text: []const u8,
start_char: CharIndex,
end_char: CharIndex,

pub fn a(start_char: CharIndex) Token {
    const self = Token{
        .token_type = undefined,
        .text = "",
        .start_char = start_char,
        .end_char = null_char_index,
    };
    return self;
}
pub fn d(self: Token) void {
    _ = self;
}

pub const TokenType = enum {
    invalid,
    identifier,
    number_literal,
    doc_comment,
    container_doc_comment,
    string_literal,
    multiline_string_literal,
    char_literal,
    builtin,
    bang,
    equal,
    equal_equal,
    equal_angle_bracket_right,
    bang_equal,
    l_paren,
    r_paren,
    semicolon,
    l_brace,
    r_brace,
    l_brace_r_brace,
    l_bracket,
    r_bracket,
    period,
    period_asterisk,
    period_question,
    period_l_brace,
    ellipsis2,
    ellipsis3,
    pipe,
    pipe_pipe,
    pipe_equal,
    percent,
    percent_equal,
    caret,
    caret_equal,
    plus,
    plus_plus,
    plus_equal,
    minus,
    minus_equal,
    asterisk,
    asterisk_equal,
    asterisk_asterisk,
    slash,
    slash_equal,
    ampersand,
    ampersand_equal,
    arrow,
    colon,
    comma,
    question_mark,
    angle_bracket_left,
    angle_bracket_left_equal,
    angle_bracket_angle_bracket_left,
    angle_bracket_angle_bracket_left_equal,
    angle_bracket_right,
    angle_bracket_right_equal,
    angle_bracket_angle_bracket_right,
    angle_bracket_angle_bracket_right_equal,
    tilde,
    keyword_align,
    keyword_and,
    keyword_asm,
    keyword_code,
    keyword_async,
    keyword_await,
    keyword_break,
    keyword_callconv,
    keyword_catch,
    keyword_comptime,
    keyword_const,
    keyword_continue,
    keyword_defer,
    keyword_errdefer,
    keyword_else,
    keyword_enum,
    keyword_error,
    keyword_fn,
    keyword_func,
    keyword_struct,
    keyword_if,
    keyword_for,
    keyword_in,
    keyword_inline,
    keyword_include,
    keyword_import,
    keyword_pub,
    keyword_or,
    keyword_resume,
    keyword_return,
    keyword_switch,
    keyword_try,
    keyword_test,
    keyword_unreachable,
    keyword_union,
    keyword_var,
    keyword_while,
};

pub const KeywordMap = StaticStringMap.t(TokenType).a(.{
    .{
        "align",
        .keyword_align,
    },
    .{
        "and",
        .keyword_and,
    },
    .{
        "asm",
        .keyword_asm,
    },
    .{
        "async",
        .keyword_async,
    },
    .{
        "await",
        .keyword_await,
    },
    .{
        "break",
        .keyword_break,
    },
    .{
        "callconv",
        .keyword_callconv,
    },
    .{
        "catch",
        .keyword_catch,
    },
    .{
        "comptime",
        .keyword_comptime,
    },
    .{
        "const",
        .keyword_const,
    },
    .{
        "continue",
        .keyword_continue,
    },
    .{
        "defer",
        .keyword_defer,
    },
    .{
        "else",
        .keyword_else,
    },
    .{
        "enum",
        .keyword_enum,
    },
    .{
        "errdefer",
        .keyword_errdefer,
    },
    .{
        "error",
        .keyword_error,
    },
    .{
        "fn",
        .keyword_fn,
    },
    .{
        "for",
        .keyword_for,
    },
    .{
        "func",
        .keyword_func,
    },
    .{
        "if",
        .keyword_if,
    },
    .{
        "import",
        .keyword_import,
    },
    .{
        "in",
        .keyword_in,
    },
    .{
        "include",
        .keyword_include,
    },
    .{
        "inline",
        .keyword_inline,
    },
    .{
        "or",
        .keyword_or,
    },
    .{
        "pub",
        .keyword_pub,
    },
    .{
        "resume",
        .keyword_resume,
    },
    .{
        "return",
        .keyword_return,
    },
    .{
        "struct",
        .keyword_struct,
    },
    .{
        "switch",
        .keyword_switch,
    },
    .{
        "test",
        .keyword_test,
    },
    .{
        "try",
        .keyword_try,
    },
    .{
        "unreachable",
        .keyword_unreachable,
    },
    .{
        "union",
        .keyword_union,
    },
    .{
        "var",
        .keyword_var,
    },
    .{
        "while",
        .keyword_while,
    },
    .{
        "code",
        .keyword_code,
    },
});
pub const OperatorMap = StaticStringMap.t(TokenType).a(.{
    .{
        "(",
        .l_paren,
    },
    .{
        ")",
        .r_paren,
    },
    .{
        "=",
        .equal,
    },
    .{
        "+",
        .plus,
    },
    .{
        "++",
        .plus_plus,
    },
    .{
        "-",
        .minus,
    },
    .{
        "*",
        .asterisk,
    },
    .{
        "/",
        .slash,
    },
    .{
        "%",
        .percent,
    },
    .{
        "!",
        .bang,
    },
    .{
        "|",
        .pipe,
    },
    .{
        "==",
        .equal_equal,
    },
    .{
        "!=",
        .bang_equal,
    },
    .{
        "^",
        .caret,
    },
    .{
        "&",
        .ampersand,
    },
    .{
        "<",
        .angle_bracket_left,
    },
    .{
        "<=",
        .angle_bracket_left_equal,
    },
    .{
        "<<",
        .angle_bracket_angle_bracket_left,
    },
    .{
        "<<=",
        .angle_bracket_angle_bracket_left_equal,
    },
    .{
        ">",
        .angle_bracket_right,
    },
    .{
        ">=",
        .angle_bracket_right_equal,
    },
    .{
        ">>",
        .angle_bracket_angle_bracket_right,
    },
    .{
        ">>=",
        .angle_bracket_angle_bracket_right_equal,
    },
    .{
        "~",
        .tilde,
    },
    .{
        ":",
        .colon,
    },
    .{
        ",",
        .comma,
    },
});

const Token = @This();
